baseURL = "https://hatebu.kkeisuke.com/"
languageCode = "ja"
title = "kkeisuke's はてなブックマーク"

[markup]
  defaultMarkdownHandler = "blackfriday"
  [markup.blackfriday]
    hrefTargetBlank = true
    noreferrerLinks = true

[minify]
  disableJS = true # 0.85 から無いと minify で error になる
