baseURL = "https://hatebu.kkeisuke.com/"
languageCode = "ja"
title = "kkeisuke's はてなブックマーク"

[markup]
  defaultMarkdownHandler = "blackfriday"
  [markup.blackfriday]
    hrefTargetBlank = true
    noreferrerLinks = true
